minimum_pre_commit_version: "4.6.2"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-added-large-files
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: mixed-line-ending
        args:
          - --fix=lf
        exclude: '(?i)\.(bat|cmd)$'

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.2
    hooks:
      - id: markdownlint-cli2
        args:
          - --fix

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        files: '(^|/)(.*\.rs|\.?rustfmt\.toml)$'
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --locked --all-targets --all-features -- -D warnings
        language: system
        files: '(^|/)(.*\.rs|Cargo\.(toml|lock)|\.?clippy\.toml)$'
        pass_filenames: false
